"""User review: selected references, preserved V2 and new actual asset-derived model."""
import json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[1];SRC=ROOT/'design/asset_model_v3';RENDER=ROOT/'renders/whole_house_final_study_v1';OUT=RENDER/'asset_model_v3';OUT.mkdir(exist_ok=True)
manifest=json.loads((SRC/'review_renders/render-manifest.json').read_text())
labels={'CAM_living_VIEW_01':'客厅 · 资产复用版主图','LD_CAM_living_DETAIL':'客厅 · 供应商软包分件与木框','AM2_CAM_SOFA_MATERIAL':'布艺 · 原生材质与真实织纹','CAM_kitchen_VIEW_01':'厨房 · 白蜡木、台面和金属','CAM_kitchen_VIEW_05':'厨房 · 双燃气灶与设备细节'}
for r in manifest['images']:
 im=Image.open(r['path']).convert('RGB');im.save(OUT/(r['camera']+'.jpg'),quality=94)
sources=[(RENDER/'whole_house_modes_v3/living/A_faithful/VIEW_01.png','living-ref-A'),(RENDER/'whole_house_modes_v3/living/B_designer/VIEW_01.png','living-ref-B'),(RENDER/'whole_house_modes_v3/kitchen/A_faithful/VIEW_01.png','kitchen-ref-A'),(RENDER/'appearance_match_v2/CAM_living_VIEW_01.jpg','living-V2'),(RENDER/'appearance_match_v2/AM2_CAM_SOFA_MATERIAL.jpg','linen-V2'),(SRC/'SUPPLIER_NATIVE_MATERIAL_TEST.png','supplier-native-test')]
for p,n in sources:
 im=Image.open(p).convert('RGB');im.thumbnail((1500,1100));im.save(OUT/(n+'.jpg'),quality=90)
def card(n,label):
 return f'<article><h2>{label}</h2><a href="{n}.jpg" target="_blank"><img src="{n}.jpg" loading="lazy"></a></article>'
html='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C-Type 客厅与厨房 · 资产复用 V3</title><style>body{margin:0;background:#f4f0e8;color:#252622;font-family:system-ui,sans-serif}main{max-width:1600px;margin:auto;padding:28px}h1{font-size:28px}h2{font-size:17px}p{line-height:1.75}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.pair{grid-template-columns:repeat(2,minmax(0,1fr))}article{padding:16px;background:white;border-radius:12px}img{width:100%;height:auto;display:block}aside{padding:18px;background:#e9dfcd;border-radius:10px}table{width:100%;border-collapse:collapse;background:white;margin:24px 0}th,td{text-align:left;padding:13px;border-bottom:1px solid #ded8cd}@media(max-width:800px){.grid,.pair{grid-template-columns:1fr}}</style><main><h1>C-Type · 客厅与厨房资产复用模型 V3</h1><p>2026-10-10 · 真实模型决定尺寸，选定效果图约束颜色、材料、质感与光影。</p><aside>本轮按用户消息中的开放式厨房与客厅制作。V1、V2、源模型均保留。客厅八个软包分件采用厂家 OBJ 的坐垫 / 背垫轮廓，按原包络适配，原木框、家具数量与位置保持。白蜡木和布艺复用供应商原生 Blender 材质节点；供应商额外抱枕未加入。本轮为可编辑候选，尚未宣称满足全部 1:1 外观要求。</aside><h1>客厅同机位对照</h1><div class="grid">'''+card('living-ref-A','已选 A · 主体家具外观')+card('living-V2','保留的 V2')+card('CAM_living_VIEW_01','V3 · 真实 Cycles 渲染')+'''</div><h1>软包形态与布艺近景</h1><div class="grid pair">'''+card('LD_CAM_living_DETAIL',labels['LD_CAM_living_DETAIL'])+card('AM2_CAM_SOFA_MATERIAL',labels['AM2_CAM_SOFA_MATERIAL'])+'''</div><h1>厨房外观与设备</h1><div class="grid">'''+card('kitchen-ref-A','既有 Faithful 厨房参考')+card('CAM_kitchen_VIEW_01',labels['CAM_kitchen_VIEW_01'])+card('CAM_kitchen_VIEW_05',labels['CAM_kitchen_VIEW_05'])+'''</div><h1>复用来源及采用项</h1><table><tr><th>部分</th><th>实际来源与实现</th><th>边界</th></tr><tr><td>客厅软包</td><td>&Tradition Fly SC2 官方 OBJ 分件：两种坐垫 / 背垫部件轮廓、浅褶皱和收边；分件调整到原模型包络</td><td>仅借用软包，未把 Fly 木框或额外抱枕替换进住宅；不是采购定款</td></tr><tr><td>布艺</td><td>Poly Haven rough_linen 原生 Blender 节点，保留实测反射、粗糙度、纤维方向、法线与 0.5 mm 原始位移；主要贴图 4K，织物高度 .3 m</td><td>蓝色扫描只做米白燕麦色适配；精确实物布料型号未定</td></tr><tr><td>白蜡木</td><td>Poly Haven ash_veneer 原生节点，1 m 尺度与顺构造木纹；原户家具 / 橱柜尺寸不变</td><td>扫描为饰面，不把它称作每个端面或榫接的精确扫描</td></tr><tr><td>厨房</td><td>原橱柜、台面、门窗、设备中心；精细边缘、金属表面、双燃气灶锅架 / 火盖 / 旋钮、烟机滤网 / 控制区和柜下灯槽</td><td>设备依据已研究厂家照片局部细化；外观参考，SKU / 开孔 / 安装尺寸未认证</td></tr><tr><td>台面</td><td>检索库未找到符合当前素净浅色台面的材质，本轮沿用项目已有石材表达并局部调整</td><td>此项为定制基线，仍需材质实样 / 单件进一步验证</td></tr></table><h1>来源测试与软装选择</h1><div class="grid pair">'''+card('supplier-native-test','隔离测试 · 厂家原始家具与供应商原生材质')+card('living-ref-B','已选 B · 窗帘、地毯、东墙画')+'''</div><p>五张 1920×1080 实渲，Cycles / Apple M4 Metal / 128 samples / OIDN High Accurate。重新打开校验 1826 个既有网格与世界矩阵保留、977 个登记源对象不变、八个供应商软包在原包络内。新设备细节和灯具是展示派生，不升级为施工 / 安全认证。</p><p>下一步逐项判断软包轮廓与布艺厚重感、白蜡木色与纹理、厨房台面 / 金属 / 灯光是否接近选定图。画作、地毯图案和现场窗外景观仍有差距；当前不重跑其他房间。</p></main></html>'''
(OUT/'review_gallery.html').write_text(html)
contact=Image.new('RGB',(1500,920),'#f7f3eb');draw=ImageDraw.Draw(contact)
for i,n in enumerate(['CAM_living_VIEW_01','LD_CAM_living_DETAIL','AM2_CAM_SOFA_MATERIAL','CAM_kitchen_VIEW_01','CAM_kitchen_VIEW_05']):
 im=Image.open(OUT/(n+'.jpg'));im.thumbnail((490,390));x=i%3*500;y=i//3*450;contact.paste(im,(x,y+25));draw.text((x+8,y+7),n,fill='#252622')
contact.save(SRC/'V3_REVIEW_CONTACT.jpg',quality=86)
print(OUT/'review_gallery.html')
